Feature creditcardmask
serilog-contrib/Serilog.Enrichers.Sensitive pull request #2
Opened 2020-09-24 21:53 UTC by stoberman37

Hi. I loved your implementation (for the most part, anyway).  I needed to add a CreditCard mask.  I also tweaked the encrich registration methods to allow others to add their own mask operators as well.

2020-10-10 14:03 UTC, sandermvanvliet commented
Hi @stoberman37 I've finally had time to take a look at the PR, thanks for adding the credit card mask I'm sure many people would find that useful!

I realize that that the README is lacking in the _how do I extend this?_ area and only shows how you can use this as is. That of course leaves everything open to interpretation ;-)

I've added some comments throughout the PR, let me know if they are clear or if I can clarify further.

Also I would suggest to run code cleanup / format document on the code you change before creating the PR. Partially because I'm a bit OCD with alignment and things like that but it also makes things a easier to review as you're not getting triggered by indentation changes in the diffs 😄 

Again, thanks for this 👍 I really appreciate it and it's always great to see that this is useful to someone!

2020-10-10 14:03 UTC, sandermvanvliet requested changes

2020-10-10 14:03 UTC, sandermvanvliet commented on test/ConsoleApp1/Program.cs
> +﻿using System;
I think this was not intentionally included, could you perhaps remove the `test/ConsoleApp1` folder?

2020-10-10 14:03 UTC, sandermvanvliet commented on src/Serilog.Enrichers.Sensitive/Serilog.Enrichers.Sensitive.csproj
> +    <Version>0.3.0</Version>
Because of the change in the logger configuration extension methods the package now has a breaking API change. I would recommend at this stage to keep the original one in addition to the methods you added there for backwards compatibility.
I think semver says something along the lines of _if it's < 1.0 then all bets are off_ but I'd like to prevent breaking changes at this point.

2020-10-10 14:03 UTC, sandermvanvliet commented on test/ConsoleApp1/Serilog.Enrichers.Sensitive.Tests.Benchmark/Program.cs
> +﻿using System.Text.RegularExpressions;
I think this benchmark was added to the existing benchmark app right? 
If not I would suggest to include it there.

2020-10-10 14:03 UTC, sandermvanvliet commented on test/Serilog.Enrichers.Sensitive.Tests.Benchmark/Program.cs
> +        public string CreditCardPartialRegexReplace()
Rather than adding a lot of methods to the `Program` class I would suggest to move these ones to `CreditCardMarkingBenchmarks` and call that in the `Main` like:

```csharp
var summary = BenchmarkRunner.Run<CreditCardMarkingBenchmarks>();
```

2020-10-10 14:03 UTC, sandermvanvliet commented on test/Serilog.Enrichers.Sensitive.Tests.Unit/WhenMaskingEmailAddresses.cs
> +        public void GivenValidEmailAddress_AddressIsMasked(string email)
Thanks for adding these :+1:

2020-10-10 14:03 UTC, sandermvanvliet commented on test/Serilog.Enrichers.Sensitive.Tests.Unit/WhenMaskingWithRegexOperator.cs
> +	    public void ConstructorParameterTests(Regex regex, string replacementPattern, string missingParameter)
I would prefer for tests like these to write them out rather than using a `Theory`.
With the current set up the reader is left to jump to the `ConstructorParameterData` class to see what kinds of input parameters would trigger what exception.

2020-10-10 14:03 UTC, sandermvanvliet commented on test/Serilog.Enrichers.Sensitive.Tests.Unit/WhenMaskingWithRegexOperator.cs
> +	    public void GivenBeforeMask_CancelsOperation()
I would not recommend to test a call like this but rather to test the results.

If you would refactor the way that the regex operator works internally you'd have to change the tests too because they are coupled to the implementation. This means that your tests are now tightly coupled to the implementation rather than the results of the _unit_ you're testing.

Given that the early exit you're trying to verify here is a performance characteristic I would expect that to be asserted in the benchmark where you verify the performance criteria rather than a unit test which asserts that an internal cancel flag is set.

2020-10-10 14:03 UTC, sandermvanvliet commented on src/Serilog.Enrichers.Sensitive/RegexMaskingOperator.cs
> +	public class RegexMaskingOperator : IMaskingOperator
The go-to pattern for re-usable implementations for me is to use an abstract base class that defines extension points for specific behavior. That allows an inheritor to easily provide the implementations for the specific parts of the overall operator.

For example consider a base class like this:

```cshrap
public abstract class RegexMaskingOperator : IMaskingOperator
{
    private readonly Regex _regex;

    protected RegexMaskingOperator()
    {
        _regex = new Regex(Regex, RegexOptions.Compiled);
    }

    protected abstract string Regex { get; }

    public MaskingResult Mask(string input, string mask)
    {
        var preprocessedInput = PreprocessInput(input);

        if (!ShouldMaskInput(preprocessedInput))
        {
            return MaskingResult.NoMatch;
        }

        var maskedResult = _regex.Replace(preprocessedInput, mask);

        var result = new MaskingResult
        {
            Result = maskedResult,
            Match = maskedResult != input
        };

        return result;
    }

    protected virtual bool ShouldMaskInput(string input)
    {
        return true;
    }

    protected virtual string PreprocessInput(string input)
    {
        return input;
    }
}
```

When implementing a masking operator that is based on a regex, the implementor then only needs to specify the regex and at the same time has the option to perform input preprocessing or early exit:

```csharp
public class EmailMaskingOperator : RegexMaskingOperator
{
    protected override string Regex = "something dummy here";

    protected override string ProcessInput(string input)
    {
        if (input.Contains("%40"))
        {
            input = input.Replace("%40", "@");
        }
    }

    protected override string ShouldMaskInput(string input)
    {
        return input.Contains("@");
    }
}
```

The advantage of using the abstract class and virtual method approach is that the generic implementation of the masking operator remains the same and at the same time it provides clear extension points by using the language features of abstract and virtual that should feel natural to other developers building on top of this.

2020-10-12 01:11 UTC, stoberman37 commented on src/Serilog.Enrichers.Sensitive/RegexMaskingOperator.cs
> +	public class RegexMaskingOperator : IMaskingOperator
I will refactor with this approach.  The only part I don't care for is it forces users to an an explicit extension for each new Regex-based filter, but that's a minor inconvenience at worst.

2020-10-12 01:13 UTC, stoberman37 commented on src/Serilog.Enrichers.Sensitive/Serilog.Enrichers.Sensitive.csproj
> +    <Version>0.3.0</Version>
This was totally an oversight on my part when I did the commit; I thought one of my subsequent commits had bumped this.  Definitely this qualifies as point release.

2020-10-12 01:15 UTC, stoberman37 commented on test/ConsoleApp1/Program.cs
> +﻿using System;
definitely was not intentional.  I will remove.

2020-10-12 01:17 UTC, stoberman37 commented on src/Serilog.Enrichers.Sensitive/RegexMaskingOperator.cs
> +	public class RegexMaskingOperator : IMaskingOperator
That said, I did have to extend the pattern a bit to add a PreprocessMask override as well, to support controlling how credit cards are masked.  I have use cases where a full mask is not quite what we need.

2020-10-12 02:08 UTC, stoberman37 commented on test/ConsoleApp1/Serilog.Enrichers.Sensitive.Tests.Benchmark/Program.cs
> +﻿using System.Text.RegularExpressions;
I did.  I'll double check it's in the pull request.

2020-10-12 02:13 UTC, stoberman37 commented on test/Serilog.Enrichers.Sensitive.Tests.Benchmark/Program.cs
> +        public string CreditCardPartialRegexReplace()
Done.

2020-10-12 02:15 UTC, stoberman37 commented on test/Serilog.Enrichers.Sensitive.Tests.Unit/WhenMaskingWithRegexOperator.cs
> +	    public void ConstructorParameterTests(Regex regex, string replacementPattern, string missingParameter)
In my day job, when writing a number of these, I find this approach to be preferable; it eliminates a lot of copy/paste repeated code.  That said, with the refactor that you suggested earlier, I was able to refactor these unit tests and got rid of the ClassData.  There is is still one test with InlineData, but I think still address your objection.

2020-10-12 02:16 UTC, stoberman37 commented on test/Serilog.Enrichers.Sensitive.Tests.Unit/WhenMaskingWithRegexOperator.cs
> +	    public void GivenBeforeMask_CancelsOperation()
with the refactor, this should not longer be relevant.

2020-10-12 03:12 UTC, stoberman37 commented
I believe that last commit should address all your comments.  I included an update to the README.md with a quick explanation of how to extend to additional use cases.

2020-10-12 14:58 UTC, sandermvanvliet commented on src/Serilog.Enrichers.Sensitive/Serilog.Enrichers.Sensitive.csproj
> +    <Version>0.3.0</Version>
My bad, think my diff view threw me off here.

2020-10-12 15:03 UTC, sandermvanvliet commented on test/Serilog.Enrichers.Sensitive.Tests.Unit/WhenMaskingWithRegexOperator.cs
> +	    public void ConstructorParameterTests(Regex regex, string replacementPattern, string missingParameter)
Much better, I don't mind the `InlineData` btw as in those cases the input is close to the test.

2020-10-12 15:03 UTC, sandermvanvliet approved these changes

2020-10-12 15:04 UTC, merged